<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AssemblyName>osu.Game.Rulesets.Orbit</AssemblyName>
    <RootNamespace>osu.Game.Rulesets.Orbit</RootNamespace>
    
    <!-- Memaksa robot GitHub mencari langsung ke gudang internal ppy osu! -->
    <RestoreSources>
      https://nuget.org;
      https://ppy.sh
    </RestoreSources>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ppy.osu.Game" Version="2026.916.0" />
  </ItemGroup>
</Project>

