name: Cloud Compile to DLL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get Repository Source Code
      uses: actions/checkout@v4

    - name: Enable Microsoft .NET Environment
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Download Framework Packages
      run: |
        dotnet add package ppy.osu.Game --version 2026.115.0 --source https://nuget.org

    - name: Compile C# Source into DLL File
      run: |
        dotnet build --configuration Release --output ./build-output

    - name: Prepare Direct Download Link
      uses: actions/upload-artifact@v4
      with:
        name: osu-orbit-ready-dll
        path: ./build-output/*.dll

