name: Build osu!orbit Ruleset

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET 10.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Install Linux Graphics Libraries
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-dev libx11-dev libxrandr-dev libxcursor-dev libxinerama-dev libxi-dev

    - name: Compile Ruleset DLL
      run: dotnet build -c Release
      env:
        DOTNET_CLI_TELEMETRY_OPTOUT: 1

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: osu-orbit-dll
        path: bin/Release/net10.0/*.dll

